package com.mmva.newsapp.infrastructure.monetization.ads.local.dto;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.mmva.newsapp.infrastructure.monetization.ads.local.enums.AdCreativeType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

/**
 * DTO for Ad Creative response data.
 *
 * @author MMVA Team
 * @since 1.0.0
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AdCreativeResponseDto {

    // ========================================
    // Basic Information
    // ========================================

    /**
     * Unique identifier for the creative.
     */
    private UUID adCreativeId;

    /**
     * Unique code for this creative.
     */
    private String adCreativeCode;

    /**
     * Human-readable name for the creative.
     */
    private String adCreativeName;

    /**
     * Detailed description of the creative content.
     */
    private String adCreativeDescription;

    // ========================================
    // Creative Details
    // ========================================

    /**
     * Type of creative.
     */
    private AdCreativeType adCreativeType;

    /**
     * Display name for the creative type.
     */
    private String adCreativeTypeDisplayName;

    /**
     * Full URL to access the creative file.
     */
    private String adCreativeFileUrl;

    /**
     * Full URL to access the creative thumbnail.
     */
    private String adCreativeThumbnailUrl;

    /**
     * Alternative text for accessibility.
     */
    private String adCreativeAltText;

    /**
     * Click destination URL when ad is clicked.
     */
    private String adCreativeClickUrl;

    // ========================================
    // Technical Specifications
    // ========================================

    /**
     * Width in pixels.
     */
    private Integer adCreativeWidth;

    /**
     * Height in pixels.
     */
    private Integer adCreativeHeight;

    /**
     * Dimensions as display string (e.g., "728x90").
     */
    private String adCreativeDimensionsDisplay;

    /**
     * File size in bytes.
     */
    private Long adCreativeFileSizeBytes;

    /**
     * File size formatted for display (e.g., "2.5 MB").
     */
    private String adCreativeFileSizeDisplay;

    /**
     * MIME type of the creative file.
     */
    private String adCreativeMimeType;

    /**
     * For video creatives: duration in seconds.
     */
    private Integer adCreativeDurationSeconds;

    /**
     * Duration formatted for display (e.g., "00:30").
     */
    private String adCreativeDurationDisplay;

    // ========================================
    // Status & Approval
    // ========================================

    /**
     * Whether this creative is active and can be served.
     */
    private Boolean adCreativeIsActive;

    /**
     * Whether this creative requires approval before use.
     */
    private Boolean adCreativeRequiresApproval;

    /**
     * Approval status: PENDING, APPROVED, REJECTED.
     */
    private String adCreativeApprovalStatus;

    /**
     * Reason for rejection if applicable.
     */
    private String adCreativeRejectionReason;

    /**
     * Whether this creative is currently available for serving.
     */
    private Boolean adCreativeIsAvailable;

    // ========================================
    // Performance Metrics
    // ========================================

    /**
     * Total impressions served for this creative.
     */
    private Long adCreativeTotalImpressions;

    /**
     * Total clicks received by this creative.
     */
    private Long adCreativeTotalClicks;

    /**
     * Click-through rate percentage.
     */
    private Double adCreativeClickThroughRate;

    /**
     * CTR formatted for display (e.g., "2.45%").
     */
    private String adCreativeClickThroughRateDisplay;

    /**
     * Total revenue generated by this creative.
     */
    private BigDecimal adCreativeTotalRevenue;

    /**
     * Revenue formatted for display (e.g., "$1,234.56").
     */
    private String adCreativeTotalRevenueDisplay;

    /**
     * Average revenue per thousand impressions.
     */
    private BigDecimal adCreativeRevenuePerMille;

    /**
     * RPM formatted for display.
     */
    private String adCreativeRevenuePerMilleDisplay;

    /**
     * Last time this creative was served.
     */
    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss'Z'", timezone = "UTC")
    private Instant adCreativeLastServedAt;

    // ========================================
    // Metadata & Integration
    // ========================================

    /**
     * Additional metadata as JSON string.
     */
    private String adCreativeMetadataJson;

    /**
     * External creative ID from ad server.
     */
    private String adCreativeExternalCreativeId;

    /**
     * External ad server name.
     */
    private String adCreativeExternalAdServer;

    /**
     * Native ad title for structured content ads.
     */
    private String adCreativeAdTitle;

    /**
     * Native ad media URL for structured content ads.
     */
    private String adCreativeAdMediaUrl;

    /**
     * Native ad summary for structured content ads.
     */
    private String adCreativeAdSummary;

    // ========================================
    // Audit Information
    // ========================================

    /**
     * When this creative was created.
     */
    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss'Z'", timezone = "UTC")
    private Instant adCreativeCreatedAt;

    /**
     * Who created this creative.
     */
    private UUID adCreativeCreatedBy;

    /**
     * When this creative was last updated.
     */
    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss'Z'", timezone = "UTC")
    private Instant adCreativeUpdatedAt;

    /**
     * Who last updated this creative.
     */
    private UUID adCreativeUpdatedBy;

    // ========================================
    // Multi-tenancy
    // ========================================

    /**
     * Tenant identifier.
     */
    private String adCreativeTenantId;
}