package com.mmva.newsapp.domain.news.dto.core;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.AllArgsConstructor;
import lombok.experimental.SuperBuilder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.UUID;

import io.swagger.v3.oas.annotations.media.Schema;

@Data
@SuperBuilder(toBuilder = true)
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class NewsCreateResponseDto {
    @Schema(description = "Unique identifier of the newsapp", example = "123e4567-e89b-12d3-a456-426614174000")
    private UUID newsNewsId;

    @Schema(description = "News title in English", example = "Global Market Update")
    private String newsTitleEn;

    @Schema(description = "News content in English", example = "The global markets saw a significant...")
    private String newsContentEn;

    @Schema(description = "HTML-formatted content for English (web-optimized)", example = "<p>The global markets saw a significant...</p>")
    private String newsContentHtmlEn;

    @Schema(description = "News title in Spanish", example = "Actualización del Mercado Global")
    private String newsTitleEs;

    @Schema(description = "News content in Spanish", example = "Los mercados globales experimentaron...")
    private String newsContentEs;

    @Schema(description = "HTML-formatted content for Spanish (web-optimized)", example = "<p>Los mercados globales experimentaron...</p>")
    private String newsContentHtmlEs;

    @Schema(description = "Content format enumeration", example = "PLAIN_TEXT")
    private String newsContentFormat;

    @Schema(description = "Manual excerpt in English", example = "Global markets experienced significant volatility...")
    private String newsExcerptEn;

    @Schema(description = "Manual excerpt in Spanish", example = "Los mercados globales experimentaron una volatilidad significativa...")
    private String newsExcerptEs;

    @Schema(description = "Whether excerpt was auto-generated", example = "true")
    private Boolean newsExcerptAutoGenerated;

    @Schema(description = "Slug for the newsapp (lowercase, hyphen-separated)", example = "global-market-update")
    private String newsSlug;

    @Schema(description = "News Category ID", example = "123e4567-e89b-12d3-a456-426614174000")
    private String newsNewsCategoryId;

    @Schema(description = "Name of the media file attached to the newsapp", example = "breaking-news_a1b2c3d4.jpg")
    private String newsMediaFileName;

    @Schema(description = "Type of the media file", example = "image/jpeg")
    private String newsMediaFileType;

    @Schema(description = "Size of the media file in bytes", example = "1048576")
    private Long newsMediaFileSize;

    @Schema(description = "Full URL to access the media file", example = "http://localhost:8080/api/v1/public/news/media/breaking-news_a1b2c3d4.jpg")
    private String newsMediaFileUrl;

    @Schema(description = "URL of the thumbnail image", example = "http://localhost:8080/api/v1/public/news/thumbnails/breaking-news_a1b2c3d4_thumb.jpg")
    private String newsThumbnailUrl;

    @Schema(description = "URL of the card size image (400x225 - 16:9)", example = "http://localhost:8080/api/v1/public/news/images/card/breaking-news_a1b2c3d4_card.jpg")
    private String newsImageCardUrl;

    @Schema(description = "URL of the hero size image (800x450 - 16:9)", example = "http://localhost:8080/api/v1/public/news/images/hero/breaking-news_a1b2c3d4_hero.jpg")
    private String newsImageHeroUrl;

    @Schema(description = "Media type (image or video)", example = "image/jpeg")
    private String newsMediaType;

    @Schema(description = "Source URL of the newsapp", example = "https://news.example.com/article/123")
    private String newsSourceUrl;

    @Schema(description = "Workflow status of the newsapp", example = "PUBLISHED")
    private String newsWorkflowStatus;

    @Schema(description = "Meta title for SEO", example = "Global Market Update - Latest News")
    private String newsMetaTitle;

    @Schema(description = "Meta description for SEO", example = "Stay updated with the latest global market newsapp and trends.")
    private String newsMetaDescription;

    @Schema(description = "SEO keywords for the newsapp", example = "market,stocks,finance,economy")
    private String newsKeywords;

    @Schema(description = "Canonical URL for SEO", example = "https://news.example.com/article/global-market-update")
    private String newsCanonicalUrl;

    @Schema(description = "Internal editor notes (admindashboard only)", example = "Needs review before publishing")
    private String newsEditorNotes;

    @Schema(description = "Comma-separated tags/labels for the newsapp", example = "Politics,Economy,Breaking News")
    private String newsTags;

    // ========================================
    // Geographic Data (Location-based News)
    // ========================================

    @Schema(description = "ISO 3166-1 alpha-2 country code", example = "US")
    private String newsCountryCode;

    @Schema(description = "Geographic region/state", example = "California")
    private String newsRegion;

    @Schema(description = "City name", example = "Los Angeles")
    private String newsCity;

    @Schema(description = "Latitude coordinate", example = "34.052235")
    private Double newsLatitude;

    @Schema(description = "Longitude coordinate", example = "-118.243683")
    private Double newsLongitude;

    @Schema(description = "Creation timestamp (ISO 8601)", example = "2024-06-01T12:34:56Z")
    private String newsCreatedAt;

    @Schema(description = "User ID of the creator", example = "987e6543-e21b-12d3-a456-426614174999")
    private UUID newsCreatedBy;

    @Schema(description = "Last update timestamp (ISO 8601)", example = "2024-06-02T08:00:00Z")
    private String newsUpdatedAt;

    @Schema(description = "User ID of the last updater", example = "987e6543-e21b-12d3-a456-426614174999")
    private UUID newsUpdatedBy;

    @Schema(description = "Publish timestamp (ISO 8601)", example = "2024-06-03T09:00:00Z")
    private String newsPublishedAt;

    @Schema(description = "User ID of the person who published the news.", example = "987e6543-e21b-12d3-a456-426614174999")
    private String newsPublishedBy;

    @Schema(description = "Scheduled publish timestamp (ISO 8601)", example = "2024-06-04T10:00:00Z")
    private String newsScheduledPublishAt;

    @Schema(description = "User ID of the person who scheduled the news for publication.", example = "987e6543-e21b-12d3-a456-426614174999")
    private String newsScheduledBy;

    // ========================================
    // Advanced Publishing Controls
    // ========================================

    @Schema(description = "Embargo until timestamp (ISO 8601)", example = "2024-06-01T18:00:00Z")
    private String newsEmbargoUntil;

    @Schema(description = "Content urgency level: LOW, NORMAL, HIGH, BREAKING", example = "NORMAL")
    private String newsUrgencyLevel;

    @Schema(description = "Target audience for content segmentation", example = "general")
    private String newsTargetAudience;

    // ========================================
    // Series Support (Multi-part Stories)
    // ========================================

    @Schema(description = "Series ID for linking related articles", example = "123e4567-e89b-12d3-a456-426614174000")
    private UUID newsSeriesId;

    @Schema(description = "Order of article within a series", example = "1")
    private Integer newsSeriesOrder;

    // ========================================
    // AUDIT: Soft Delete
    // ========================================

    @Schema(description = "Soft delete timestamp (ISO 8601)", example = "2024-06-05T15:00:00Z")
    private String newsDeletedAt;

    @Schema(description = "User ID of the deleter", example = "987e6543-e21b-12d3-a456-426614174999")
    private UUID newsDeletedBy;

    // ========================================
    // Priority & Versioning
    // ========================================

    @Schema(description = "Priority for sorting (higher = more important)", example = "0")
    private Integer newsPriority;

    @Schema(description = "Content version number", example = "1")
    private Integer newsVersion;

    @Schema(description = "ID of the previous version of this news article", example = "123e4567-e89b-12d3-a456-426614174000")
    private UUID newsPreviousVersionId;

    @Schema(description = "Whether the newsapp is featured", example = "true")
    private Boolean newsIsFeatured;

    @Schema(description = "Whether the newsapp is active", example = "true")
    private Boolean newsIsActive;

    @Schema(description = "Number of views for the newsapp", example = "1234")
    private Long newsViewCount;

    @Schema(description = "Number of times the newsapp was shared", example = "56")
    private Long newsShareCount;

    @Schema(description = "Number of likes for the newsapp", example = "789")
    private Long newsLikeCount;

    @Schema(description = "Number of comments on the newsapp", example = "42")
    private Long newsCommentCount;

    @Schema(description = "Number of bookmarks for the newsapp", example = "15")
    private Long newsBookmarkCount;

    @Schema(description = "Number of replies on comments", example = "28")
    private Long newsReplyCount;

    // ========================================
    // Breaking News
    // ========================================

    @Schema(description = "Whether this is breaking newsapp", example = "false")
    private Boolean newsIsBreaking;

    @Schema(description = "When the breaking newsapp status expires (ISO 8601)", example = "2024-06-01T18:00:00Z")
    private String newsBreakingExpiresAt;

    // ========================================
    // Content Expiration & Read Time
    // ========================================

    @Schema(description = "When this newsapp expires/auto-archives (ISO 8601)", example = "2024-12-31T23:59:59Z")
    private String newsExpiresAt;

    @Schema(description = "Estimated reading time in minutes", example = "5")
    private Integer newsReadTimeMinutes;

    @Schema(description = "When newsapp content was last edited (ISO 8601)", example = "2024-06-02T10:30:00Z")
    private String newsLastEditedAt;

    // ========================================
    // Content Quality Metrics
    // ========================================

    @Schema(description = "Total word count", example = "450")
    private Integer newsWordCount;

    @Schema(description = "Total character count", example = "2800")
    private Integer newsCharacterCount;

    @Schema(description = "Content readability score (0.0 to 10.0)", example = "7.2")
    private Double newsReadabilityScore;

    // ========================================
    // Content Origin & Attribution
    // ========================================

    @Schema(description = "Source of the content: ORIGINAL, SYNDICATED, USER_SUBMITTED, PARTNER", example = "ORIGINAL")
    private String newsContentOrigin;

    @Schema(description = "Author byline for display", example = "John Smith")
    private String newsSourceAuthorName;

    @Schema(description = "ID of the source newsapp agency", example = "123e4567-e89b-12d3-a456-426614174000")
    private UUID newsSourceAgencyId;

    @Schema(description = "Name of the source newsapp agency", example = "Reuters")
    private String newsSourceAgencyName;

    @Schema(description = "Logo URL of the source newsapp agency", example = "https://cdn.example.com/logos/reuters.png")
    private String newsSourceAgencyLogoUrl;

    // ========================================
    // Monetization - Sponsored Content
    // ========================================

    @Schema(description = "Whether this is sponsored/paid content", example = "false")
    private Boolean newsIsSponsored;

    @Schema(description = "Sponsor/advertiser name", example = "Acme Corporation")
    private String newsSponsorName;

    @Schema(description = "URL to sponsor's logo", example = "https://cdn.example.com/sponsors/acme.png")
    private String newsSponsorLogoUrl;

    @Schema(description = "CTA link to sponsor's website", example = "https://www.acme.com")
    private String newsSponsorWebsiteUrl;

    // ========================================
    // Monetization - Premium Content
    // ========================================

    @Schema(description = "Whether this content is behind a paywall", example = "false")
    private Boolean newsIsPremium;

    @Schema(description = "Minimum subscription tier required: FREE, BASIC, PRO, ENTERPRISE", example = "FREE")
    private String newsPremiumTier;

    // ========================================
    // Platform-Specific Processed Content
    // ========================================

    @Schema(description = "Mobile-optimized content in English", example = "This is mobile-optimized content...")
    private String mobileContentEn;

    @Schema(description = "Mobile-optimized content in Spanish", example = "Este es contenido optimizado para móvil...")
    private String mobileContentEs;

    @Schema(description = "Web HTML content in English", example = "<p>This is HTML content for web...</p>")
    private String webContentHtmlEn;

    @Schema(description = "Web HTML content in Spanish", example = "<p>Este es contenido HTML para web...</p>")
    private String webContentHtmlEs;

    @Schema(description = "Card excerpt in English", example = "Breaking news summary...")
    private String cardExcerptEn;

    @Schema(description = "Card excerpt in Spanish", example = "Resumen de noticia de última hora...")
    private String cardExcerptEs;
}
