package com.mmva.newsapp.domain.news.dto.core;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO for thumbnail generation response.
 * 
 * <h3>Usage:</h3>
 * Returned after thumbnail is generated from image/video or custom upload.
 * 
 * @author MMVA Team
 * @since 1.0.0
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ThumbnailResponseDto {

    /**
     * The generated thumbnail filename.
     * Pattern: {sanitized-name}_{uuid}_thumb.jpg
     */
    private String filename;

    /**
     * The full HTTP URL to access the thumbnail.
     * Example:
     * http://localhost:8080/api/v1/public/news/thumbnails/breaking-news_a1b2c3d4_thumb.jpg
     */
    private String url;

    /**
     * The file system path where thumbnail is stored.
     * Used internally, not exposed to clients.
     */
    private String filePath;

    /**
     * Original filename (before sanitization).
     */
    private String originalFilename;

    /**
     * File size in bytes.
     */
    private Long fileSize;

    /**
     * MIME type (always image/jpeg for thumbnails).
     */
    private String contentType;

    /**
     * Width of the thumbnail in pixels.
     */
    private Integer width;

    /**
     * Height of the thumbnail in pixels.
     */
    private Integer height;

    /**
     * Source type - how the thumbnail was generated.
     */
    private ThumbnailSource source;

    /**
     * Enum representing how the thumbnail was created.
     */
    public enum ThumbnailSource {
        /** Uploaded directly by user */
        CUSTOM_UPLOAD,
        /** Generated by resizing an image */
        IMAGE_RESIZE,
        /** Extracted frame from video */
        VIDEO_FRAME
    }
}
