/** Complete NewsItem model matching backend NewsCreateResponseDto - Full data synchronization */
export interface NewsItem {
  // ==================== CORE IDENTITY ====================
  newsNewsId: string;
  newsTitleEn: string;
  newsTitleEs: string;
  newsSlug: string;

  // ==================== CORE CONTENT ====================
  newsContentEn: string;
  newsContentEs: string;
  newsExcerptEn?: string;
  newsExcerptEs?: string;
  newsExcerptAutoGenerated?: boolean;
  newsContentFormat: string;

  // ==================== HTML/WEB CONTENT (for different platforms) ====================
  newsContentHtmlEn?: string;
  newsContentHtmlEs?: string;

  // ==================== CATEGORY & METADATA ====================
  newsNewsCategoryId: string;
  newsMetaTitle?: string;
  newsMetaDescription: string;
  newsKeywords: string;
  newsTags?: string;
  newsCanonicalUrl?: string;
  newsEditorNotes?: string;

  // ==================== MEDIA FILES ====================
  newsMediaFileName: string;
  newsMediaFileType: string;
  newsMediaFileSize: number;
  newsMediaFileUrl: string;
  newsMediaType: string;
  newsThumbnailUrl: string;
  newsImageCardUrl: string;
  newsImageHeroUrl: string;

  // ==================== PUBLISHING & DATES ====================
  newsSourceUrl: string;
  newsWorkflowStatus: string;
  newsCreatedAt: string;
  newsCreatedBy: string;
  newsUpdatedAt: string;
  newsUpdatedBy?: string;
  newsPublishedAt?: string;
  newsPublishedBy?: string;
  newsScheduledPublishAt?: string;
  newsScheduledBy?: string;
  newsLastEditedAt?: string;
  newsDeletedAt?: string;
  newsDeletedBy?: string;

  // ==================== ADVANCED PUBLISHING CONTROLS ====================
  newsEmbargoUntil?: string;
  newsUrgencyLevel?: string;
  newsTargetAudience?: string;

  // ==================== BREAKING NEWS ====================
  newsIsBreaking: boolean;
  newsBreakingExpiresAt?: string;

  // ==================== SERIES SUPPORT (multi-part stories) ====================
  newsSeriesId?: string;
  newsSeriesOrder?: number;

  // ==================== PRIORITY & VERSIONING ====================
  newsPriority: number;
  newsVersion: number;
  newsPreviousVersionId?: string;

  // ==================== STATUS FLAGS ====================
  newsIsFeatured: boolean;
  newsIsActive: boolean;

  // ==================== ENGAGEMENT METRICS ====================
  newsViewCount: number;
  newsShareCount: number;
  newsLikeCount: number;
  newsCommentCount: number;
  newsBookmarkCount: number;
  newsReplyCount: number;

  // ==================== CONTENT QUALITY ====================
  newsReadTimeMinutes: number;
  newsWordCount?: number;
  newsCharacterCount?: number;
  newsReadabilityScore?: number;
  newsExpiresAt?: string;

  // ==================== CONTENT ORIGIN & ATTRIBUTION ====================
  newsContentOrigin: string;
  newsSourceAuthorName?: string;
  newsSourceAgencyId?: string;
  newsSourceAgencyName?: string;
  newsSourceAgencyLogoUrl?: string;

  // ==================== MONETIZATION - SPONSORED ====================
  newsIsSponsored: boolean;
  newsSponsorName?: string;
  newsSponsorLogoUrl?: string;
  newsSponsorWebsiteUrl?: string;

  // ==================== MONETIZATION - PREMIUM ====================
  newsIsPremium: boolean;
  newsPremiumTier?: string;

  // ==================== GEOGRAPHIC DATA (location-based news) ====================
  newsCountryCode?: string;
  newsRegion?: string;
  newsCity?: string;
  newsLatitude?: number;
  newsLongitude?: number;

  // ==================== PLATFORM-SPECIFIC OPTIMIZED CONTENT ====================
  // Set by service layer after entity mapping - not stored in DB
  mobileContentEn?: string;
  mobileContentEs?: string;
  webContentHtmlEn?: string;
  webContentHtmlEs?: string;
  cardExcerptEn?: string;
  cardExcerptEs?: string;
}
