import { Injectable } from '@angular/core';
import { NewsItem } from '../models/news-item.model';

/**
 * PROFESSIONAL MAPPER: Transforms backend NewsCreateResponseDto (DTO) 
 * into application NewsItem model (ViewModel).
 * 
 * Handles:
 * - Type conversions (UUID strings to strings, dates formatting)
 * - Default values for missing/optional fields
 * - Data validation and null-safety
 * - Single source of truth for data transformation
 * 
 * @author NewsApp Team
 * @version 1.0
 * @since 2026-03-05
 */
@Injectable({ providedIn: 'root' })
export class NewsMapper {

  /**
   * Transform backend DTO to application NewsItem model.
   * 
   * Ensures:
   * - All required fields have proper types
   * - Optional fields are safely handled
   * - Defaults are applied for missing data
   * - Data consistency across the application
   * 
   * @param dto Raw DTO from backend API
   * @returns Mapped NewsItem ready for UI consumption
   */
  static fromDto(dto: any): NewsItem {
    if (!dto) {
      return this.getEmptyNewsItem();
    }

    return {
      // ==================== CORE IDENTITY ====================
      newsNewsId: dto.newsNewsId || '',
      newsTitleEn: dto.newsTitleEn || '',
      newsTitleEs: dto.newsTitleEs || '',
      newsSlug: dto.newsSlug || '',

      // ==================== CORE CONTENT ====================
      newsContentEn: dto.newsContentEn || '',
      newsContentEs: dto.newsContentEs || '',
      newsExcerptEn: dto.newsExcerptEn,
      newsExcerptEs: dto.newsExcerptEs,
      newsExcerptAutoGenerated: dto.newsExcerptAutoGenerated ?? false,
      newsContentFormat: dto.newsContentFormat || 'PLAIN_TEXT',

      // ==================== HTML/WEB CONTENT ====================
      newsContentHtmlEn: dto.newsContentHtmlEn,
      newsContentHtmlEs: dto.newsContentHtmlEs,

      // ==================== CATEGORY & METADATA ====================
      newsNewsCategoryId: dto.newsNewsCategoryId || '',
      newsMetaTitle: dto.newsMetaTitle,
      newsMetaDescription: dto.newsMetaDescription || '',
      newsKeywords: dto.newsKeywords || '',
      newsTags: dto.newsTags,
      newsCanonicalUrl: dto.newsCanonicalUrl,
      newsEditorNotes: dto.newsEditorNotes,

      // ==================== MEDIA FILES ====================
      newsMediaFileName: dto.newsMediaFileName || '',
      newsMediaFileType: dto.newsMediaFileType || '',
      newsMediaFileSize: dto.newsMediaFileSize ?? 0,
      newsMediaFileUrl: dto.newsMediaFileUrl || '',
      newsMediaType: dto.newsMediaType || '',
      newsThumbnailUrl: dto.newsThumbnailUrl || '',
      newsImageCardUrl: dto.newsImageCardUrl || '',
      newsImageHeroUrl: dto.newsImageHeroUrl || '',

      // ==================== PUBLISHING & DATES ====================
      newsSourceUrl: dto.newsSourceUrl || '',
      newsWorkflowStatus: dto.newsWorkflowStatus || 'DRAFT',
      newsCreatedAt: dto.newsCreatedAt || new Date().toISOString(),
      newsCreatedBy: dto.newsCreatedBy || '',
      newsUpdatedAt: dto.newsUpdatedAt || new Date().toISOString(),
      newsUpdatedBy: dto.newsUpdatedBy,
      newsPublishedAt: dto.newsPublishedAt,
      newsScheduledPublishAt: dto.newsScheduledPublishAt,
      newsLastEditedAt: dto.newsLastEditedAt,

      // ==================== ADVANCED PUBLISHING CONTROLS ====================
      newsEmbargoUntil: dto.newsEmbargoUntil,
      newsUrgencyLevel: dto.newsUrgencyLevel || 'NORMAL',
      newsTargetAudience: dto.newsTargetAudience,

      // ==================== BREAKING NEWS ====================
      newsIsBreaking: dto.newsIsBreaking ?? false,
      newsBreakingExpiresAt: dto.newsBreakingExpiresAt,

      // ==================== SERIES SUPPORT ====================
      newsSeriesId: dto.newsSeriesId,
      newsSeriesOrder: dto.newsSeriesOrder,

      // ==================== PRIORITY & VERSIONING ====================
      newsPriority: dto.newsPriority ?? 0,
      newsVersion: dto.newsVersion ?? 1,
      newsPreviousVersionId: dto.newsPreviousVersionId,

      // ==================== STATUS FLAGS ====================
      newsIsFeatured: dto.newsIsFeatured ?? false,
      newsIsActive: dto.newsIsActive ?? true,

      // ==================== ENGAGEMENT METRICS ====================
      newsViewCount: dto.newsViewCount ?? 0,
      newsShareCount: dto.newsShareCount ?? 0,
      newsLikeCount: dto.newsLikeCount ?? 0,
      newsCommentCount: dto.newsCommentCount ?? 0,
      newsBookmarkCount: dto.newsBookmarkCount ?? 0,
      newsReplyCount: dto.newsReplyCount ?? 0,

      // ==================== CONTENT QUALITY ====================
      newsReadTimeMinutes: dto.newsReadTimeMinutes ?? 0,
      newsWordCount: dto.newsWordCount,
      newsCharacterCount: dto.newsCharacterCount,
      newsReadabilityScore: dto.newsReadabilityScore,
      newsExpiresAt: dto.newsExpiresAt,

      // ==================== CONTENT ORIGIN & ATTRIBUTION ====================
      newsContentOrigin: dto.newsContentOrigin || 'ORIGINAL',
      newsSourceAuthorName: dto.newsSourceAuthorName,
      newsSourceAgencyId: dto.newsSourceAgencyId,
      newsSourceAgencyName: dto.newsSourceAgencyName,
      newsSourceAgencyLogoUrl: dto.newsSourceAgencyLogoUrl,

      // ==================== MONETIZATION - SPONSORED ====================
      newsIsSponsored: dto.newsIsSponsored ?? false,
      newsSponsorName: dto.newsSponsorName,
      newsSponsorLogoUrl: dto.newsSponsorLogoUrl,
      newsSponsorWebsiteUrl: dto.newsSponsorWebsiteUrl,

      // ==================== MONETIZATION - PREMIUM ====================
      newsIsPremium: dto.newsIsPremium ?? false,
      newsPremiumTier: dto.newsPremiumTier || 'FREE',

      // ==================== GEOGRAPHIC DATA ====================
      newsCountryCode: dto.newsCountryCode,
      newsRegion: dto.newsRegion,
      newsCity: dto.newsCity,
      newsLatitude: dto.newsLatitude ? parseFloat(dto.newsLatitude) : undefined,
      newsLongitude: dto.newsLongitude ? parseFloat(dto.newsLongitude) : undefined,

      // ==================== PLATFORM-SPECIFIC CONTENT ====================
      mobileContentEn: dto.mobileContentEn,
      mobileContentEs: dto.mobileContentEs,
      webContentHtmlEn: dto.webContentHtmlEn,
      webContentHtmlEs: dto.webContentHtmlEs,
      cardExcerptEn: dto.cardExcerptEn,
      cardExcerptEs: dto.cardExcerptEs,
    };
  }

  /**
   * Transform array of DTOs to NewsItem models.
   * 
   * @param dtos Array of backend DTOs
   * @returns Array of mapped NewsItem models
   */
  static fromDtoArray(dtos: any[]): NewsItem[] {
    if (!Array.isArray(dtos)) {
      return [];
    }
    return dtos.map(dto => this.fromDto(dto));
  }

  /**
   * Get empty NewsItem with safe defaults.
   * Used when data is unavailable or initialization.
   * 
   * @returns Empty NewsItem with defaults
   */
  static getEmptyNewsItem(): NewsItem {
    const now = new Date().toISOString();
    return {
      newsNewsId: '',
      newsTitleEn: '',
      newsTitleEs: '',
      newsSlug: '',
      newsContentEn: '',
      newsContentEs: '',
      newsContentFormat: 'PLAIN_TEXT',
      newsNewsCategoryId: '',
      newsMetaDescription: '',
      newsKeywords: '',
      newsMediaFileName: '',
      newsMediaFileType: '',
      newsMediaFileSize: 0,
      newsMediaFileUrl: '',
      newsMediaType: '',
      newsThumbnailUrl: '',
      newsImageCardUrl: '',
      newsImageHeroUrl: '',
      newsSourceUrl: '',
      newsWorkflowStatus: 'DRAFT',
      newsCreatedAt: now,
      newsCreatedBy: '',
      newsUpdatedAt: now,
      newsIsFeatured: false,
      newsIsActive: true,
      newsViewCount: 0,
      newsShareCount: 0,
      newsLikeCount: 0,
      newsCommentCount: 0,
      newsBookmarkCount: 0,
      newsReplyCount: 0,
      newsIsBreaking: false,
      newsReadTimeMinutes: 0,
      newsContentOrigin: 'ORIGINAL',
      newsIsSponsored: false,
      newsIsPremium: false,
      newsPremiumTier: 'FREE',
      newsPriority: 0,
      newsVersion: 1,
    };
  }
}
